services:
  - type: web
    name: ai-resume-analyzer
    runtime: python
    pythonVersion: 3.11.9

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_career.wsgi:application