# Generated by Django 6.0.3 on 2026-03-21 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(default='test', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('programming_languages', models.TextField(blank=True, null=True)),
                ('web_technologies', models.TextField(blank=True, null=True)),
                ('frameworks_tools', models.TextField(blank=True, null=True)),
                ('database', models.TextField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('resume_template', models.CharField(default='Default', max_length=50)),
                ('font_style', models.CharField(default='Arial', max_length=50)),
                ('font_size', models.IntegerField(default=12)),
                ('color_theme', models.CharField(default='Blue', max_length=20)),
                ('sections_order', models.TextField(blank=True, help_text='Comma separated sections order')),
                ('default_job_role', models.CharField(default='Web Developer', max_length=50)),
                ('preferred_keywords', models.TextField(blank=True, help_text='Comma separated keywords')),
                ('show_resume_score', models.BooleanField(default=True)),
                ('preferred_role', models.CharField(default='Web Developer', max_length=50)),
                ('difficulty_level', models.CharField(default='Easy', max_length=20)),
                ('enable_timer', models.BooleanField(default=False)),
                ('save_progress', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=False)),
                ('weekly_resume_tips', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
