# Generated by Django 6.0.3 on 2026-03-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='resume',
            name='achievements',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cgpa',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='college',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='course',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='database',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='frameworks_tools',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(blank=True, default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='programming_languages',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='web_technologies',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='year',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
