# Generated by Django 6.0.3 on 2026-03-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resume_score_alter_resume_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='score',
        ),
    ]
