# Generated by Django 6.0.3 on 2026-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
