# Generated by Django 6.0.3 on 2026-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resume_score_resume_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
