# Generated by Django 6.0.3 on 2026-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_performance_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='github',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='resume_format',
            field=models.CharField(default='PDF', max_length=10),
        ),
    ]
