# Generated by Django 6.0.3 on 2026-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_usersettings_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='preferred_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='sections_order',
            field=models.TextField(blank=True),
        ),
    ]
