# Generated by Django 6.0.3 on 2026-04-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usersettings_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
